export const pagesData = [
  {
    id: 0,
    name: 'Kitchen',
    slug: 'kitchen-designs',
    noItems: '2047',
    heading: 'Modular Kitchen Designs',
    desc: 'At Design Indian Homes, we craft simple modular kitchen designs that are the perfect blend of functionality and style. Our curated, modular kitchen designs in India range from simple kitchens with minimal interiors to more elaborately designed kitchen interior designs. All our modern kitchen designs can be customised to fit your budget and existing space. We also have kitchen interior designs that work for all shapes: Be it a L-shaped kitchen, U-shaped kitchen or open kitchen design - crafting a kitchen interior design that works best for your home is our goal! Browse through our top kitchen designs of 2023 to transform your space today.',
   
  },
  {
    id: 1,
    name: 'Venities',
    slug: 'master-bedroom',
    noItems: '2874',
    heading: 'Bedroom Interior Designs',
    desc: 'At Livspace, we’ve got a wide range of affordable and stylish bedroom designs that you’ll love. Our carefully-curated master bedroom designs come in a variety of styles, colour schemes and decor ideas - all of which can be customised to your taste. Whether you’re looking for a contemporary style or a room with rustic sensibilities, we’ve got all the bedroom interior design inspiration you’ll need to create a space that reflects your personality and taste. Take your pick from these trending designs and start your bedroom renovation journey today with Livspace.',
    items: [],
  },
  {
    id: 2,
    name: 'Crockery Units',
    slug: 'living-room',
    noItems: '1816',
    heading: 'Crockery Units',
    desc: 'Discover a wide range of handpicked, living room interior designs and décor ideas at Livspace. We bring you living room designs that are customizable, practical and trendy. From modular TV units to wall paintings and living room wall designs, you’ll find all the inspiration you’ll need to get started. Browse now to zero in on your favourite design and create a living room space that reflects your style.',
    items: [],
  },
  {
    id: 3,
    name: 'Glass Partiton',
    slug: 'homes',
    noItems: '162',
    heading: '2,3 & 4BHK Home Interior Designs by Livspace',
    desc: 'With over 75,000 happy homes delivered, Livspace helps you build your dream home in your design and style. Browse through the homes we have delivered for some inspiration. Customised, budget-friendly home designs delivered across cities. Be it renovation or a full home design, apartment or villa home, we have got you covered.',
    items: [],
  },
  {
    id: 4,
    name: 'Bathroom',
    slug: 'bathroom',
    noItems: '809',
    heading: 'Bathroom Designs',
    desc: 'Livspace brings you bathroom interior designs that are functional and also stylish. Whether you’re looking for small bathroom ideas or spacious ones, we’ve created some elegant bathroom designs for you to consider for your next home renovation project.',
    items: [],
  },
  {
    id: 5,
    name: 'Study room designs',
    slug: 'study-room-design',
    noItems: '123',
    heading: 'Study Room Design Ideas',
    desc: 'Welcome to Livspace Study Room Designs category, where we offer a treasure trove of study room ideas to inspire your perfect space. Explore modern study room designs, featuring stylish decor, furniture, and smart organization solutions. Whether you are seeking study room design inspiration, trendy study room decor ideas, or functional study room furniture, we have you covered. Discover the latest trends in modern study room design and transform your study space into a productive and stylish oasis with our expert tips and curated collection.',
    items: [],
  },
  {
    id: 6,
    name: 'Wardrobe',
    slug: 'wardrobe',
    noItems: '1165',
    heading: 'Wardrobe Interior Designs',
    desc: 'Livspace design ideas is your one-stop shop for wardrobe solutions. Our modular wardrobe designs are ergonomically designed and come in a wide spectrum of colours, finishes and materials. Built for smart storage, our cupboard designs are function-forward, easy to use and promise to make stunning additions to the spaces in your bedroom. Explore our extensive collection of wardrobe interior designs and find one you can customise for your bedroom today.',
    items: [],
  },
  {
    id: 7,
    name: 'Tv unit designs',
    slug: 'tv-unit-designs',
    noItems: '1012',
    heading: 'Modular TV Unit Design Ideas',
    desc: 'Trending TV unit designs from Livspace that can be customised to your style, preference and TV sizes. TV units are essential piece of furniture that serves as a focal point for your room while giving you amazing storage options. From wall-mounted TV unit designs for the living room to TV cupboard units in the hall and traditional TV cabinets for your bedroom, Livspace helps you create a functional and stylish TV unit. Browse through our budget-friendly modern TV unit designs that will help you transform the look of your home.',
    items: [],
  },
  {
    id: 8,
    name: 'Kids bedroom',
    slug: 'kids-bedroom',
    noItems: '1053',
    heading: 'Kids Bedroom Designs',
    desc: 'Designing your kid’s bedroom space can be an exciting time for you and your child. We’re certain you’ll find a healthy dose of inspiration and trending kid’s room designs that will match your childs personality! Our handpicked, affordable kid’s bedroom designs can be customised to suit your space requirements and your child’s imagination. Get in touch with our experts today to build a bedroom that your child will love.',
    items: [],
  },
]
