export const pagesData = [
  {
    id: 0,
    name: 'Kitchen',
    slug: 'kitchen-designs',
    noItems: '2047',
    heading: 'Modular Kitchen Designs',
    desc: 'At Design Indian Homes, we craft simple modular kitchen designs that are the perfect blend of functionality and style. Our curated, modular kitchen designs in India range from simple kitchens with minimal interiors to more elaborately designed kitchen interior designs. All our modern kitchen designs can be customised to fit your budget and existing space. We also have kitchen interior designs that work for all shapes: Be it a L-shaped kitchen, U-shaped kitchen or open kitchen design - crafting a kitchen interior design that works best for your home is our goal! Browse through our top kitchen designs of 2023 to transform your space today.',
    items: [
      {
        designId: 'zxcvbnm',
        heading:
          'Contemporary Gothic Grey and Frosty White Modular Kitchen design',
        size: '12x8',
        image: '/designImages/63-1702272240-NwfHr.avif',
      },
      {
        designId: '2',
        heading:
          'Contemporary Gothic Grey and Frosty White Modular Kitchen design',
        size: '12x8',
        image: '/designImages/64-1702272241-905ht.avif',
      },
      {
        designId: '3',
        heading:
          'Contemporary Gothic Grey and Frosty White Modular Kitchen design',
        size: '12x8',
        image: '/designImages/65-1702272242-zYaZf.avif',
      },
    ],
  },
  {
    id: 1,
    name: 'Master bedroom',
    slug: 'master-bedroom',
    noItems: '2874',
    heading: 'Bedroom Interior Designs',
    desc: 'At Livspace, we’ve got a wide range of affordable and stylish bedroom designs that you’ll love. Our carefully-curated master bedroom designs come in a variety of styles, colour schemes and decor ideas - all of which can be customised to your taste. Whether you’re looking for a contemporary style or a room with rustic sensibilities, we’ve got all the bedroom interior design inspiration you’ll need to create a space that reflects your personality and taste. Take your pick from these trending designs and start your bedroom renovation journey today with Livspace.',
    items: [],
  },
  {
    id: 2,
    name: 'Living room',
    slug: 'living-room',
    noItems: '1816',
    heading: 'Living Room Interior Designs',
    desc: 'Discover a wide range of handpicked, living room interior designs and décor ideas at Livspace. We bring you living room designs that are customizable, practical and trendy. From modular TV units to wall paintings and living room wall designs, you’ll find all the inspiration you’ll need to get started. Browse now to zero in on your favourite design and create a living room space that reflects your style.',
    items: [],
  },
  {
    id: 3,
    name: 'Homes',
    slug: 'homes',
    noItems: '162',
    heading: '2,3 & 4BHK Home Interior Designs by Livspace',
    desc: 'With over 75,000 happy homes delivered, Livspace helps you build your dream home in your design and style. Browse through the homes we have delivered for some inspiration. Customised, budget-friendly home designs delivered across cities. Be it renovation or a full home design, apartment or villa home, we have got you covered.',
    items: [],
  },
  {
    id: 4,
    name: 'Bathroom',
    slug: 'bathroom',
    noItems: '809',
    heading: 'Bathroom Designs',
    desc: 'Livspace brings you bathroom interior designs that are functional and also stylish. Whether you’re looking for small bathroom ideas or spacious ones, we’ve created some elegant bathroom designs for you to consider for your next home renovation project.',
    items: [],
  },
  {
    id: 5,
    name: 'Study room designs',
    slug: 'study-room-design',
    noItems: '123',
    heading: 'Study Room Design Ideas',
    desc: 'Welcome to Livspace Study Room Designs category, where we offer a treasure trove of study room ideas to inspire your perfect space. Explore modern study room designs, featuring stylish decor, furniture, and smart organization solutions. Whether you are seeking study room design inspiration, trendy study room decor ideas, or functional study room furniture, we have you covered. Discover the latest trends in modern study room design and transform your study space into a productive and stylish oasis with our expert tips and curated collection.',
    items: [],
  },
  {
    id: 6,
    name: 'Wardrobe',
    slug: 'wardrobe',
    noItems: '1165',
    heading: 'Wardrobe Interior Designs',
    desc: 'Livspace design ideas is your one-stop shop for wardrobe solutions. Our modular wardrobe designs are ergonomically designed and come in a wide spectrum of colours, finishes and materials. Built for smart storage, our cupboard designs are function-forward, easy to use and promise to make stunning additions to the spaces in your bedroom. Explore our extensive collection of wardrobe interior designs and find one you can customise for your bedroom today.',
    items: [],
  },
  {
    id: 7,
    name: 'Tv unit designs',
    slug: 'tv-unit-designs',
    noItems: '1012',
    heading: 'Modular TV Unit Design Ideas',
    desc: 'Trending TV unit designs from Livspace that can be customised to your style, preference and TV sizes. TV units are essential piece of furniture that serves as a focal point for your room while giving you amazing storage options. From wall-mounted TV unit designs for the living room to TV cupboard units in the hall and traditional TV cabinets for your bedroom, Livspace helps you create a functional and stylish TV unit. Browse through our budget-friendly modern TV unit designs that will help you transform the look of your home.',
    items: [],
  },
  {
    id: 8,
    name: 'Kids bedroom',
    slug: 'kids-bedroom',
    noItems: '1053',
    heading: 'Kids Bedroom Designs',
    desc: 'Designing your kid’s bedroom space can be an exciting time for you and your child. We’re certain you’ll find a healthy dose of inspiration and trending kid’s room designs that will match your childs personality! Our handpicked, affordable kid’s bedroom designs can be customised to suit your space requirements and your child’s imagination. Get in touch with our experts today to build a bedroom that your child will love.',
    items: [],
  },
  {
    id: 9,
    name: 'False ceiling design',
    slug: 'false-ceiling-designs',
    noItems: '724',
    heading: 'Modern False Ceiling Designs',
    desc: 'False ceiling designs can help you change the look of any room. Be it living rooms or bedrooms, adding false ceiling designs are a great way to give your ceilings better definition and lighting. From POP designs to layered and peripheral false ceilings, we have a range of handpicked false ceiling design ideas for you to choose from. With Livspace, discover trending, modern false ceiling designs, that fit your space and budget',
    items: [],
  },
  {
    id: 10,
    name: 'Pooja room',
    slug: 'pooja-room',
    noItems: '524',
    heading: 'Pooja Room Designs',
    desc: 'A pooja room serves as a sanctuary for peace and prayer and we know just how to translate these attributes into our pooja room designs. If you are looking for a space rooted in Indian tradition, or something with a contemporary aesthetic, we’ve got you covered! Browse through our wide range of affordable and customisable mandir designs for your home. Get cost estimates for free with Livspace.',
    items: [],
  },
  {
    id: 11,
    name: 'Dining room',

    slug: 'dining-room',
    noItems: '1166',
    heading: 'Dining Room Designs & Décor',
    desc: 'It is often believed that a family that eats together, stays together, thereby making the dining room one of the most indispensable areas in a house! Whether you are looking for a compact dining unit or a spacious one, here’s your daily dose of dining room interior design inspiration to start your home interior journey today.',
    items: [],
  },
  {
    id: 12,
    name: 'Foyer',
    slug: 'foyer',
    noItems: '807',
    heading: 'Foyer Designs',
    desc: 'With our unique foyer designs that pack both style and function, you’ll have a beautiful and well-organized entryway to make that stunning first impression. Here are some inspiring foyer design ideas to get you started.',
    items: [],
  },
  {
    id: 13,
    name: 'Guest bedroom',
    slug: 'guest-bedroom',
    noItems: '888',
    heading: 'Guest Room Designs',
    desc: 'Your guest room is an extension of your hospitality and should be thoughtfully designed to make all your guests feel welcome and at home. Browse through some stylish guest room designs from Livspace to spark some inspiration for your next home renovation project or for your new home.',
    items: [],
  },
  {
    id: 14,
    name: 'Home office',
    slug: 'home-office',
    noItems: '633',
    heading: 'Home Office Designs',
    desc: 'A smartly designed home office not only inspires creativity but also helps you reach your peak productivity. Whether you want it to be minimalistic or modern, we can help you get the look you desire. Here are some home office designs to get inspired from',
    items: [],
  },
  {
    id: 15,
    name: 'Balcony',
    slug: 'balcony',
    noItems: '198',
    heading: 'Home Balcony Designs',
    desc: 'Whether you choose to use your balcony as a reading nook, a spot for a sundowner or for fresco dining purposes, Livspace has all the latest balcony designs to turn your balcony into your favourite place in the house. Check out our latest balcony designs that reflect your personal style.',
    items: [],
  },
  {
    id: 16,
    name: 'Tile design',
    slug: 'tile-design',
    noItems: '488',
    heading: 'Tile Designs for Walls & Floors',
    desc: 'Tiles can do so much more than serve the basic function of keeping your spaces beautiful. We believe that every surface is an extension of your artistic expression & personality, which is why it is important to treat your rooms to quality tile designs. No matter how big or small your project is, we have got you covered. Browse through Livspace latest floor and wall tile designs and take your pick! We have tile designs in every colour, shape, finish - crafted & engineered to perfection.',
    items: [],
  },
  {
    id: 17,
    name: 'Wall paint design',
    slug: 'wall-paint-design',
    noItems: '332',
    heading: 'Home Wall Paint Design Ideas',
    desc: 'Keep your walls looking fresh with our exquisite range of wall paints. From smooth interior emulsions to distempers and designer finishes, we have got all the inspiration you will ever need to give your rooms the colours they deserve. Discover a wide range of wall paint and wall colour combinations for all your home painting needs and for every one of your spaces. Get a solid colour for your master bedroom or a fun, colour-blocked wall for your kids bedroom. Be creative with patterns, designs and finishes. If you have the idea, we have the colours. If you have a wall, we have got the wall paint designs!',
    items: [],
  },
  {
    id: 18,
    name: 'Wallpaper design',
    slug: 'wallpaper-design',
    noItems: '452',
    heading: 'Wallpaper Design for Home Wall Decor',
    desc: 'Wallpapers can add colour to your walls, giving it a personality of its own. If you have always wanted to decorate your wall with fun, quirky prints, now is your chance to do it. From animal prints to floral patterns & abstract wallpaper designs, each wallpaper has a story to tell and can add beauty to your everyday spaces. Scroll through our exquisitely curated collection of the latest, handpicked wallpaper designs and transform your rooms today! We have wallpapers for all wall sizes and rooms and we promise you will be spoilt for choice with our extensive catalogue of trending wallpaper designs.',
    items: [],
  },
  {
    id: 19,
    name: 'Wall decor ideas',
    slug: 'wall-decor-ideas',
    noItems: '306',
    heading: 'Best Wall Decor Ideas for Home',
    desc: 'Looking for wall design ideas and décor to refresh your blank walls? Empty walls are filled with possibilities and we have got just the right wall designs to amp up your spaces, while bringing out the best in each room. While a bare wall can feel refreshing—especially when a room is filled with bold furniture, printed area rugs, and plenty of objects, having your walls treated to artwork, refreshing panelling or designer textures, can add character and dimension to your spaces. Now, in just a few simple steps, you can bring style to every square inch of your space, including your walls! From statement art pieces to whimsical wallpaper and everything else in between, every wall design here is packed with visual intrigue.',
    items: [],
  },
  {
    id: 20,
    name: 'Flooring design',
    slug: 'flooring-design',
    noItems: '201',
    heading: 'Latest Floor Design Ideas for Home',
    desc: 'Your floors are the largest surfaces in your home, and picking the best type of flooring for your space depends on your budget, lifestyle and personal preferences. Each type of flooring has its unique benefits, and determining which flooring is best for your space, depends on each room’s interior design plan and location. Be it for aesthetic purposes or safety reasons, getting the right flooring to match your interiors is a crucial step. Browse through our extensive catalogue of handpicked, curated flooring. Pick from vinyl flooring, tiles, wood flooring to carpet flooring and granite. We have got something for every floor!',
    items: [],
  },
  {
    id: 21,
    name: 'Window design',
    slug: 'window-design',
    noItems: '182',
    heading: 'Window Design Ideas for Home',
    desc: 'Create beautiful exteriors and warm inviting interiors with our latest catalogue of window designs. While windows are essential for ventilation, they are also a crucial aesthetic component, enhancing the functionality of your home. At Livspace, you will find windows for different rooms and spaces. Personalise your windows based on your unique preferences, shape requirements and pair it with your existing interiors. Here, you will discover trending window glass designs, sliding windows & wooden window designs, that can all help transform your space. With the promise of plenty of natural sunlight and fresh air, our latest window designs will make unique, aesthetic additions to the rooms in your house.',
    items: [],
  },
]
