export const pagesData = [
  {
    id: 0,
    name: 'Wooden Polishing',
    slug: '/wooden-polishing',
    noItems: '2047',
    heading: 'Wooden Polishing',
    desc: 'At Design Indian Homes, we craft simple modular kitchen designs that are the perfect blend of functionality and style. Our curated, modular kitchen designs in India range from simple kitchens with minimal interiors to more elaborately designed kitchen interior designs. All our modern kitchen designs can be customised to fit your budget and existing space. We also have kitchen interior designs that work for all shapes: Be it a L-shaped kitchen, U-shaped kitchen or open kitchen design - crafting a kitchen interior design that works best for your home is our goal! Browse through our top kitchen designs of 2023 to transform your space today.',
   
  },
  {
    id: 1,
    name: 'Wooden Flooring',
    slug: '/wooden-flooring',
    noItems: '2874',
    heading: 'Wooden Flooring',
    desc: 'At Livspace, we’ve got a wide range of affordable and stylish bedroom designs that you’ll love. Our carefully-curated master bedroom designs come in a variety of styles, colour schemes and decor ideas - all of which can be customised to your taste. Whether you’re looking for a contemporary style or a room with rustic sensibilities, we’ve got all the bedroom interior design inspiration you’ll need to create a space that reflects your personality and taste. Take your pick from these trending designs and start your bedroom renovation journey today with Livspace.',
    items: [],
  },
  {
    id: 2,
    name: 'vertical Garden',
    slug: '/vertical-garden',
    noItems: '1816',
    heading: 'vertical Garden',
    desc: 'Discover a wide range of handpicked, living room interior designs and décor ideas at Livspace. We bring you living room designs that are customizable, practical and trendy. From modular TV units to wall paintings and living room wall designs, you’ll find all the inspiration you’ll need to get started. Browse now to zero in on your favourite design and create a living room space that reflects your style.',
    items: [],
  },
  {
    id: 3,
    name: 'UPVC Windows',
    slug: '/upvc-window',
    noItems: '162',
    heading: 'UPVC Windows',
    desc: 'With over 75,000 happy homes delivered, Livspace helps you build your dream home in your design and style. Browse through the homes we have delivered for some inspiration. Customised, budget-friendly home designs delivered across cities. Be it renovation or a full home design, apartment or villa home, we have got you covered.',
    items: [],
  },
  {
    id: 4,
    name: 'Tiling Designs',
    slug: '/tiling-design',
    noItems: '809',
    heading: 'Tiling Designs',
    desc: 'Livspace brings you bathroom interior designs that are functional and also stylish. Whether you’re looking for small bathroom ideas or spacious ones, we’ve created some elegant bathroom designs for you to consider for your next home renovation project.',
    items: [],
  },
  {
    id: 5,
    name: 'Sofa Designs',
    slug: '/sofa-designs',
    noItems: '1165',
    heading: 'Sofa Designs',
    desc: 'Livspace design ideas is your one-stop shop for wardrobe solutions. Our modular wardrobe designs are ergonomically designed and come in a wide spectrum of colours, finishes and materials. Built for smart storage, our cupboard designs are function-forward, easy to use and promise to make stunning additions to the spaces in your bedroom. Explore our extensive collection of wardrobe interior designs and find one you can customise for your bedroom today.',
    items: [],
  },
  {
    id: 6,
    name: 'Kitchen Lightening',
    slug: '/kitchen-lightening',
    noItems: '1012',
    heading: 'Kitchen Lightening',
    desc: 'Trending TV unit designs from Livspace that can be customised to your style, preference and TV sizes. TV units are essential piece of furniture that serves as a focal point for your room while giving you amazing storage options. From wall-mounted TV unit designs for the living room to TV cupboard units in the hall and traditional TV cabinets for your bedroom, Livspace helps you create a functional and stylish TV unit. Browse through our budget-friendly modern TV unit designs that will help you transform the look of your home.',
    items: [],
  },
  {
    id: 7,
    name: 'Plumbings',
    slug: '/plumbings',
    noItems: '1012',
    heading: 'Plumbings',
    desc: 'Trending TV unit designs from Livspace that can be customised to your style, preference and TV sizes. TV units are essential piece of furniture that serves as a focal point for your room while giving you amazing storage options. From wall-mounted TV unit designs for the living room to TV cupboard units in the hall and traditional TV cabinets for your bedroom, Livspace helps you create a functional and stylish TV unit. Browse through our budget-friendly modern TV unit designs that will help you transform the look of your home.',
    items: [],
  },
  {
    id: 8,
    name: 'Glass Partitions',
    slug: '/glass-partition',
    noItems: '1012',
    heading: 'Glass Partitions',
    desc: 'Trending TV unit designs from Livspace that can be customised to your style, preference and TV sizes. TV units are essential piece of furniture that serves as a focal point for your room while giving you amazing storage options. From wall-mounted TV unit designs for the living room to TV cupboard units in the hall and traditional TV cabinets for your bedroom, Livspace helps you create a functional and stylish TV unit. Browse through our budget-friendly modern TV unit designs that will help you transform the look of your home.',
    items: [],
  },
  {
    id: 9,
    name: 'ceilings',
    slug: '/ceilings',
    noItems: '1012',
    heading: 'ceilings',
    desc: 'Trending TV unit designs from Livspace that can be customised to your style, preference and TV sizes. TV units are essential piece of furniture that serves as a focal point for your room while giving you amazing storage options. From wall-mounted TV unit designs for the living room to TV cupboard units in the hall and traditional TV cabinets for your bedroom, Livspace helps you create a functional and stylish TV unit. Browse through our budget-friendly modern TV unit designs that will help you transform the look of your home.',
    items: [],
  },
  {
    id: 10,
    name: 'Wall Panelling',
    slug: '/wall-panelling',
    noItems: '1012',
    heading: 'Wall Panelling',
    desc: 'Trending TV unit designs from Livspace that can be customised to your style, preference and TV sizes. TV units are essential piece of furniture that serves as a focal point for your room while giving you amazing storage options. From wall-mounted TV unit designs for the living room to TV cupboard units in the hall and traditional TV cabinets for your bedroom, Livspace helps you create a functional and stylish TV unit. Browse through our budget-friendly modern TV unit designs that will help you transform the look of your home.',
    items: [],
  },

  {
    id: 11,
    name: 'Exterior Cladding',
    slug: '/exterior-cladding',
    noItems: '1012',
    heading: 'Exterior-Cladding',
    desc: 'Trending TV unit designs from Livspace that can be customised to your style, preference and TV sizes. TV units are essential piece of furniture that serves as a focal point for your room while giving you amazing storage options. From wall-mounted TV unit designs for the living room to TV cupboard units in the hall and traditional TV cabinets for your bedroom, Livspace helps you create a functional and stylish TV unit. Browse through our budget-friendly modern TV unit designs that will help you transform the look of your home.',
    items: [],
  },
  {
    id: 12,
    name: 'Door',
    slug: '/doors',
    noItems: '1012',
    heading: 'Door',
    desc: 'Trending TV unit designs from Livspace that can be customised to your style, preference and TV sizes. TV units are essential piece of furniture that serves as a focal point for your room while giving you amazing storage options. From wall-mounted TV unit designs for the living room to TV cupboard units in the hall and traditional TV cabinets for your bedroom, Livspace helps you create a functional and stylish TV unit. Browse through our budget-friendly modern TV unit designs that will help you transform the look of your home.',
    items: [],
  },
  {
    id: 13,
    name: 'Electric Works',
    slug: '/electric-works',
    noItems: '1012',
    heading: 'Electric Works',
    desc: 'Trending TV unit designs from Livspace that can be customised to your style, preference and TV sizes. TV units are essential piece of furniture that serves as a focal point for your room while giving you amazing storage options. From wall-mounted TV unit designs for the living room to TV cupboard units in the hall and traditional TV cabinets for your bedroom, Livspace helps you create a functional and stylish TV unit. Browse through our budget-friendly modern TV unit designs that will help you transform the look of your home.',
    items: [],
  },
  {
    id: 14,
    name: 'Beds',
    slug: '/beds',
    noItems: '1012',
    heading: 'Beds',
    desc: 'Trending TV unit designs from Livspace that can be customised to your style, preference and TV sizes. TV units are essential piece of furniture that serves as a focal point for your room while giving you amazing storage options. From wall-mounted TV unit designs for the living room to TV cupboard units in the hall and traditional TV cabinets for your bedroom, Livspace helps you create a functional and stylish TV unit. Browse through our budget-friendly modern TV unit designs that will help you transform the look of your home.',
    items: [],
  },
  {
    id: 15,
    name: 'Paints',
    slug: '/paints',
    noItems: '1012',
    heading: 'Paints',
    desc: 'Trending TV unit designs from Livspace that can be customised to your style, preference and TV sizes. TV units are essential piece of furniture that serves as a focal point for your room while giving you amazing storage options. From wall-mounted TV unit designs for the living room to TV cupboard units in the hall and traditional TV cabinets for your bedroom, Livspace helps you create a functional and stylish TV unit. Browse through our budget-friendly modern TV unit designs that will help you transform the look of your home.',
    items: [],
  },
  {
    id: 16,
    name: 'End to End Interiors',
    slug: '/end-to-end-interiors',
    noItems: '1012',
    heading: 'End to End Interiors',
    desc: 'Trending TV unit designs from Livspace that can be customised to your style, preference and TV sizes. TV units are essential piece of furniture that serves as a focal point for your room while giving you amazing storage options. From wall-mounted TV unit designs for the living room to TV cupboard units in the hall and traditional TV cabinets for your bedroom, Livspace helps you create a functional and stylish TV unit. Browse through our budget-friendly modern TV unit designs that will help you transform the look of your home.',
    items: [],
  },
  
  {
    id: 17,
    name: 'Commercial Interiors',
    slug: '/commercial-interiors',
    noItems: '1012',
    heading: 'Commercial Interiors',
    desc: 'Trending TV unit designs from Livspace that can be customised to your style, preference and TV sizes. TV units are essential piece of furniture that serves as a focal point for your room while giving you amazing storage options. From wall-mounted TV unit designs for the living room to TV cupboard units in the hall and traditional TV cabinets for your bedroom, Livspace helps you create a functional and stylish TV unit. Browse through our budget-friendly modern TV unit designs that will help you transform the look of your home.',
    items: [],
  },
]
