export const pagesData = [
  {
    id: 0,
    name: 'Structural Renovation',
    slug: '/structural-renovation',
    noItems: '2',
    heading: 'Structural Renovation',
    desc: 'Transform your space with our expert structural renovation services. From foundation to roof, we specialize in enhancing the structural integrity of your property.',
    items: [],
  },
  {
    id: 1,
    name: 'Interior Renovation',
    slug: '/interior-renovation',
    noItems: '4',
    heading: 'Interior Renovation',
    desc: 'Elevate the aesthetics of your interiors with our professional interior renovation services. We focus on creating spaces that are both functional and visually appealing.',
    items: [],
  },
  {
    id: 2,
    name: 'Bedroom Renovation',
    slug: '/bedroom-renovation',
    noItems: '5',
    heading: 'Bedroom Renovation',
    desc: 'Redefine your personal space with our tailored bedroom renovation solutions. We bring style and comfort together to create the bedroom of your dreams.',
    items: [],
  },
  {
    id: 3,
    name: 'Lounge Renovation',
    slug: '/lounge-renovation',
    noItems: '6',
    heading: 'Lounge Renovation',
    desc: 'Upgrade your lounge area with our expert renovation services. We focus on creating inviting and relaxing spaces for entertainment and leisure.',
    items: [],
  },
  {
    id: 4,
    name: 'Bathroom Renovation',
    slug: '/bathroom-renovation',
    noItems: '7',
    heading: 'Bathroom Renovation',
    desc: 'Experience luxury and functionality with our bathroom renovation services. From modern designs to functional layouts, we transform bathrooms into soothing retreats.',
    items: [],
  },
  {
    id: 5,
    name: 'Terrace Renovation',
    slug: '/terrace-renovation',
    noItems: '6',
    heading: 'Terrace Renovation',
    desc: 'Revitalize your outdoor space with our terrace renovation expertise. Whether it\'s a cozy balcony or a spacious terrace, we create areas for relaxation and entertainment.',
    items: [],
  },
  {
    id: 6,
    name: 'Living Room Renovation',
    slug: '/living-room-renovation',
    noItems: '57',
    heading: 'Living Room Renovation',
    desc: 'Infuse new life into your living room with our renovation services. From furniture arrangement to color schemes, we transform living spaces into stylish and comfortable areas.',
    items: [],
  },
  {
    id: 7,
    name: 'Modular Kitchen Renovation',
    slug: '/modular-kitchen-renovation',
    noItems: '87',
    heading: 'Modular Kitchen Renovation',
    desc: 'Upgrade your kitchen with our modular kitchen renovation solutions. We combine functionality and style to create efficient and beautiful kitchen spaces.',
    items: [],
  },
  {
    id: 8,
    name: 'Wardrobe Renovation',
    slug: '/wardrobe-renovation',
    noItems: '564',
    heading: 'Wardrobe Renovation',
    desc: 'Organize and revamp your storage space with our wardrobe renovation services. We design and install custom wardrobe solutions to suit your needs.',
    items: [],
  },
  {
    id: 9,
    name: 'Mandir Renovation',
    slug: '/mandir-renovation',
    noItems: '345',
    heading: 'Mandir Renovation',
    desc: 'Enhance the spiritual ambiance of your home with our mandir renovation services. We create sacred spaces that reflect your devotion and style.',
    items: [],
  },
  {
    id: 10,
    name: 'GYM & Spas Renovation',
    slug: '/gym-spas-renovation',
    noItems: '768',
    heading: 'GYM & Spas Renovation',
    desc: 'Transform your fitness and relaxation spaces with our renovation expertise. From gyms to spas, we create environments that promote well-being.',
    items: [],
  },
  {
    id: 11,
    name: 'Hotel Renovation',
    slug: '/hotel-renovation',
    noItems: '345',
    heading: 'Hotel Renovation',
    desc: 'Elevate the guest experience with our hotel renovation services. We focus on creating welcoming and stylish spaces for hospitality.',
    items: [],
  },
  {
    id: 12,
    name: 'Farmhouse Renovation',
    slug: '/farmhouse-renovation',
    noItems: '345',
    heading: 'Farmhouse Renovation',
    desc: 'Transform your farmhouse into a retreat with our renovation services. We enhance both the interior and exterior for a harmonious and inviting atmosphere.',
    items: [],
  },
  {
    id: 13,
    name: 'Banquet Renovation',
    slug: '/banquet-renovation',
    noItems: '453',
    heading: 'Banquet Renovation',
    desc: 'Upgrade your event space with our banquet renovation services. We create elegant and functional venues for various celebrations.',
    items: [],
  },
  {
    id: 14,
    name: 'Villa Renovation',
    slug: '/villa-renovation',
    noItems: '6576',
    heading: 'Villa Renovation',
    desc: 'Revitalize your villa with our renovation expertise. We focus on enhancing both the interior and exterior to create a luxurious and comfortable living space.',
    items: [],
  },
  
]
